/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bigw.javalambda;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

public class Handler implements RequestHandler<Request, Response> {

	@Override
	public Response handleRequest(Request input, Context context) {
		return new Response(input.getInput());
	}
	
}